import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { getServerSession } from "next-auth";
import { AuthProvider } from "../providers/AuthProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>{children}</AuthProvider>
            {/* Add a simple sidebar for navigation */}
            <nav style={{ position: 'fixed', left: 0, top: 0, height: '100vh', width: 180, background: '#f5f5f5', padding: 16 }}>
              <a href="/">Dashboard</a><br />
              <a href="/links">Links & Docs</a><br />
              <a href="/tools">Tools</a><br />
              <a href="/login">Logout</a>
            </nav>
            <div style={{ marginLeft: 200 }}>{children}</div>
      </body>
    </html>
  );
}
